/**
 * Created by jmartinez on 12/11/17.
 */
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGOUT_USER = "LOGOUT_USER";
export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const TOGGLE_PASSWORD_RESET = "TOGGLE_PASSWORD_RESET";
export const SUBMIT_PASSWORD_RESET_SUCCESS = "SUBMIT_PASSWORD_RESET_SUCCESS";
export const SUBMIT_PASSWORD_RESET_FAIL = "SUBMIT_PASSWORD_RESET_FAIL";
export const SUBMIT_PASSWORD_RESET_REQUEST = "SUBMIT_PASSWORD_RESET_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SUCCESS= "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";
export const LOAD_CURRENT_USERS = "LOAD_CURRENT_USERS";
export const UPDATE_ROLE_SUCCESS = "UPDATE_ROLE_SUCCESS";
export const UPDATE_ROLE_FAIL = "UPDATE_ROLE_FAIL";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const roleOptions = [
    {value: "Admin", name: "Admin"},
    {value: "Modeler", name: "Modeler"}
];
