/**
 * Created by jmartinez on 1/10/18.
 */
export const SUBMIT_MODEL_CONFIG_SUCCESS = "SUBMIT_MODEL_CONFIG_SUCCESS";
export const SUBMIT_MODEL_CONFIG_FAIL = "SUBMIT_MODEL_CONFIG_FAIL";
export const SUBMIT_MODEL_CONFIG_REQUEST = "SUBMIT_MODEL_CONFIG_REQUEST";
export const UPDATE_MODEL_STATUS = "UPDATE_MODEL_STATUS";