/**
 * Created by jmartinez on 1/10/18.
 */
export const SUBMIT_MODEL_CONFIG_SUCCESS = "SUBMIT_MODEL_CONFIG_SUCCESS";
export const SUBMIT_MODEL_CONFIG_FAIL = "SUBMIT_MODEL_CONFIG_FAIL";
export const SUBMIT_MODEL_CONFIG_REQUEST = "SUBMIT_MODEL_CONFIG_REQUEST";
export const UPDATE_MODEL_STATUS = "UPDATE_MODEL_STATUS";
export const FORM_ERROR = "FORM_ERROR";
export const SUBMIT_EC2_REQUEST = "SUBMIT_EC2_REQUEST";
export const SUBMIT_EC2_SUCCESS = "SUBMIT_EC2_SUCCESS";
export const SUBMIT_EC2_FAIL = "SUBMIT_EC2_FAIL";
export const UPDATE_RESOURCE_STATUS = "UPDATE_RESOURCE_STATUS";
export const UPDATE_NO_RESOURCES = "UPDATE_NO_RESOURCES";
export const CLOSE_MODAL = "CLOSE_MODAL";